// <auto-generated />
using System;
using AniQueue.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AniQueue.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AniQueueDbContext))]
    [Migration("20260819194034_AddAnimeRelations")]
    partial class AddAnimeRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("AniQueue.Core.Domain.Anime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverImageColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EpisodeDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleEnglish")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleNative")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleRomaji")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.ToTable("Anime");
                });

            modelBuilder.Entity("AniQueue.Core.Domain.AnimeExternalId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("MissingFromSourceAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RelationsFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId", "Source")
                        .IsUnique()
                        .HasDatabaseName("IX_AnimeExternalIds_AnimeId_Source");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("IX_AnimeExternalIds_Source_ExternalId");

                    b.ToTable("AnimeExternalIds");
                });

            modelBuilder.Entity("AniQueue.Core.Domain.AnimeRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("RelationType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Source", "RelatedExternalId");

                    b.HasIndex("Source", "ExternalId", "RelationType", "RelatedExternalId")
                        .IsUnique();

                    b.ToTable("AnimeRelations");
                });

            modelBuilder.Entity("AniQueue.Core.Domain.LibraryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateCompleted")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateStarted")
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodesWatched")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastWrittenBySource")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersonalNotes")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("RecommendationConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("RecommendationReason")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<double?>("RecommendationScore")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset?>("RecommendationUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.HasIndex("ProfileId", "AnimeId")
                        .IsUnique()
                        .HasDatabaseName("IX_LibraryEntries_ProfileId_AnimeId");

                    b.HasIndex("ProfileId", "IsHidden");

                    b.HasIndex("ProfileId", "RecommendationScore");

                    b.HasIndex("ProfileId", "Status");

                    b.ToTable("LibraryEntries", t =>
                        {
                            t.HasCheckConstraint("CK_LibraryEntries_UserScoreRange", "\"UserScore\" IS NULL OR (\"UserScore\" >= 1 AND \"UserScore\" <= 10)");
                        });
                });

            modelBuilder.Entity("AniQueue.Core.Domain.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("AniQueue.Core.Domain.ProfileSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DateFormat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultQueueSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultRecommendationMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludePersonalNotesInAiExport")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreferredTitleLanguage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Theme")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("ProfileSettings");
                });

            modelBuilder.Entity("AniQueue.Core.Domain.QueueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("AnimeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.HasIndex("ProfileId", "AnimeId")
                        .IsUnique()
                        .HasDatabaseName("IX_QueueItems_ProfileId_AnimeId");

                    b.HasIndex("ProfileId", "Position")
                        .HasDatabaseName("IX_QueueItems_ProfileId_Position");

                    b.ToTable("QueueItems");
                });

            modelBuilder.Entity("AniQueue.Core.Domain.RecommendationRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidateCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletedCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelIdentifier")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ResultCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WasApplied")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "CreatedAt");

                    b.ToTable("RecommendationRuns");
                });

            modelBuilder.Entity("AniQueue.Core.Domain.RecommendationRunItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimeId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<double>("PredictedScore")
                        .HasColumnType("REAL");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("RunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.HasIndex("RunId", "Rank");

                    b.ToTable("RecommendationRunItems", t =>
                        {
                            t.HasCheckConstraint("CK_RecommendationRunItems_ConfidenceRange", "\"Confidence\" >= 0.0 AND \"Confidence\" <= 1.0");

                            t.HasCheckConstraint("CK_RecommendationRunItems_RankPositive", "\"Rank\" >= 1");
                        });
                });

            modelBuilder.Entity("AniQueue.Core.Domain.SourceSyncSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AbsencePolicy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ApplyUnattended")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConflictPolicy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrecedenceRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Schedule")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "Source")
                        .IsUnique()
                        .HasDatabaseName("IX_SourceSyncSettings_ProfileId_Source");

                    b.ToTable("SourceSyncSettings");
                });

            modelBuilder.Entity("AniQueue.Core.Domain.SyncRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AbsentFlagged")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChangesHeld")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConflictsHeld")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Skipped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotsReleased")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Updated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "Source")
                        .HasDatabaseName("IX_SyncRuns_ProfileId_Source");

                    b.ToTable("SyncRuns");
                });

            modelBuilder.Entity("AniQueue.Core.Domain.AnimeExternalId", b =>
                {
                    b.HasOne("AniQueue.Core.Domain.Anime", "Anime")
                        .WithMany("ExternalIds")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("AniQueue.Core.Domain.LibraryEntry", b =>
                {
                    b.HasOne("AniQueue.Core.Domain.Anime", "Anime")
                        .WithMany()
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AniQueue.Core.Domain.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("AniQueue.Core.Domain.ProfileSettings", b =>
                {
                    b.HasOne("AniQueue.Core.Domain.Profile", "Profile")
                        .WithOne("Settings")
                        .HasForeignKey("AniQueue.Core.Domain.ProfileSettings", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("AniQueue.Core.Domain.QueueItem", b =>
                {
                    b.HasOne("AniQueue.Core.Domain.Anime", "Anime")
                        .WithMany()
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AniQueue.Core.Domain.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("AniQueue.Core.Domain.RecommendationRun", b =>
                {
                    b.HasOne("AniQueue.Core.Domain.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniQueue.Core.Domain.RecommendationRunItem", b =>
                {
                    b.HasOne("AniQueue.Core.Domain.Anime", "Anime")
                        .WithMany()
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AniQueue.Core.Domain.RecommendationRun", "Run")
                        .WithMany("Items")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("AniQueue.Core.Domain.SourceSyncSettings", b =>
                {
                    b.HasOne("AniQueue.Core.Domain.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("AniQueue.Core.Domain.SyncRun", b =>
                {
                    b.HasOne("AniQueue.Core.Domain.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("AniQueue.Core.Domain.Anime", b =>
                {
                    b.Navigation("ExternalIds");
                });

            modelBuilder.Entity("AniQueue.Core.Domain.Profile", b =>
                {
                    b.Navigation("Settings");
                });

            modelBuilder.Entity("AniQueue.Core.Domain.RecommendationRun", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
