// <auto-generated />
using System;
using AniQueue.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AniQueue.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AniQueueDbContext))]
    partial class AniQueueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("AniQueue.Core.Domain.Anime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlternativeTitle")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EpisodeDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FranchiseId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FranchiseOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OptionalWithinFranchise")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceAnimeId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("Title");

                    b.HasIndex("Source", "SourceAnimeId")
                        .IsUnique()
                        .HasDatabaseName("IX_Anime_Source_SourceAnimeId")
                        .HasFilter("\"SourceAnimeId\" IS NOT NULL");

                    b.ToTable("Anime");
                });

            modelBuilder.Entity("AniQueue.Core.Domain.Franchise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ManualSortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManualSortOrder");

                    b.HasIndex("Name");

                    b.ToTable("Franchises");
                });

            modelBuilder.Entity("AniQueue.Core.Domain.LibraryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateCompleted")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateStarted")
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodesWatched")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("ManualPriority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersonalNotes")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("RecommendationConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("RecommendationReason")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<double?>("RecommendationScore")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset?>("RecommendationUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.HasIndex("ProfileId", "AnimeId")
                        .IsUnique()
                        .HasDatabaseName("IX_LibraryEntries_ProfileId_AnimeId");

                    b.HasIndex("ProfileId", "IsHidden");

                    b.HasIndex("ProfileId", "RecommendationScore");

                    b.HasIndex("ProfileId", "Status");

                    b.ToTable("LibraryEntries", t =>
                        {
                            t.HasCheckConstraint("CK_LibraryEntries_UserScoreRange", "\"UserScore\" IS NULL OR (\"UserScore\" >= 1 AND \"UserScore\" <= 10)");
                        });
                });

            modelBuilder.Entity("AniQueue.Core.Domain.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("AniQueue.Core.Domain.ProfileSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DateFormat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultQueueSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultRecommendationMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludePersonalNotesInAiExport")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowOptionalFranchiseEntries")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Theme")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("ProfileSettings");
                });

            modelBuilder.Entity("AniQueue.Core.Domain.QueueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AnimeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FranchiseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("ProfileId", "AnimeId")
                        .IsUnique()
                        .HasDatabaseName("IX_QueueItems_ProfileId_AnimeId")
                        .HasFilter("\"AnimeId\" IS NOT NULL");

                    b.HasIndex("ProfileId", "FranchiseId")
                        .IsUnique()
                        .HasDatabaseName("IX_QueueItems_ProfileId_FranchiseId")
                        .HasFilter("\"FranchiseId\" IS NOT NULL");

                    b.HasIndex("ProfileId", "Position")
                        .HasDatabaseName("IX_QueueItems_ProfileId_Position");

                    b.ToTable("QueueItems", t =>
                        {
                            t.HasCheckConstraint("CK_QueueItems_AnimeXorFranchise", "(\"AnimeId\" IS NULL) <> (\"FranchiseId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("AniQueue.Core.Domain.RecommendationRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidateCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletedCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelIdentifier")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ResultCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WasApplied")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "CreatedAt");

                    b.ToTable("RecommendationRuns");
                });

            modelBuilder.Entity("AniQueue.Core.Domain.RecommendationRunItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AnimeId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<int?>("FranchiseId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PredictedScore")
                        .HasColumnType("REAL");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("RunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("RunId", "Rank");

                    b.ToTable("RecommendationRunItems", t =>
                        {
                            t.HasCheckConstraint("CK_RecommendationRunItems_AnimeXorFranchise", "(\"AnimeId\" IS NULL) <> (\"FranchiseId\" IS NULL)");

                            t.HasCheckConstraint("CK_RecommendationRunItems_ConfidenceRange", "\"Confidence\" >= 0.0 AND \"Confidence\" <= 1.0");

                            t.HasCheckConstraint("CK_RecommendationRunItems_RankPositive", "\"Rank\" >= 1");
                        });
                });

            modelBuilder.Entity("AniQueue.Core.Domain.Anime", b =>
                {
                    b.HasOne("AniQueue.Core.Domain.Franchise", "Franchise")
                        .WithMany("Entries")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("AniQueue.Core.Domain.LibraryEntry", b =>
                {
                    b.HasOne("AniQueue.Core.Domain.Anime", "Anime")
                        .WithMany()
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AniQueue.Core.Domain.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("AniQueue.Core.Domain.ProfileSettings", b =>
                {
                    b.HasOne("AniQueue.Core.Domain.Profile", "Profile")
                        .WithOne("Settings")
                        .HasForeignKey("AniQueue.Core.Domain.ProfileSettings", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("AniQueue.Core.Domain.QueueItem", b =>
                {
                    b.HasOne("AniQueue.Core.Domain.Anime", "Anime")
                        .WithMany()
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AniQueue.Core.Domain.Franchise", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AniQueue.Core.Domain.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("AniQueue.Core.Domain.RecommendationRun", b =>
                {
                    b.HasOne("AniQueue.Core.Domain.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniQueue.Core.Domain.RecommendationRunItem", b =>
                {
                    b.HasOne("AniQueue.Core.Domain.Anime", "Anime")
                        .WithMany()
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AniQueue.Core.Domain.Franchise", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AniQueue.Core.Domain.RecommendationRun", "Run")
                        .WithMany("Items")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("Franchise");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("AniQueue.Core.Domain.Franchise", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("AniQueue.Core.Domain.Profile", b =>
                {
                    b.Navigation("Settings");
                });

            modelBuilder.Entity("AniQueue.Core.Domain.RecommendationRun", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
